[project]
name = "multimodal-chat-assistant-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.5.0",
    "gradio>=5.20.1",
    "pillow>=11.1.0",
    "pydantic-settings[yaml]>=2.8.1",
]
